name: Calculator CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # -------------------------
  # CI
  # -------------------------
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore CalculatorCICD/CalculatorCICD.slnx

      - name: Build
        run: dotnet build CalculatorCICD/CalculatorCICD.slnx --no-restore

      - name: Run tests
        run: dotnet test CalculatorCICD/CalculatorCICD.slnx --no-build
 
    # -------------------------
    # Delivery
    # ------------------------- 
  publish:
    needs: build-and-test    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Publish application
        run: dotnet publish CalculatorCICD/CalculatorCICD.csproj -c Release -o ./publish
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-app
          path: ./publish
