name: Calculator CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore CalculatorCICD/CalculatorCICD.sln

      - name: Build
        run: dotnet build CalculatorCICD/CalculatorCICD.sln --no-restore

      - name: Run tests
        run: dotnet test CalculatorCICD/CalculatorCICD.sln --no-build
